"""empty message

Revision ID: 8660b8acb173
Revises: 5127c6edc9b2
Create Date: 2022-10-10 10:22:18.296882

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8660b8acb173'
down_revision = '5127c6edc9b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('bike', sa.Column('longitude', sa.Float(), nullable=True))
    op.drop_column('bike', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike', sa.Column('location', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('bike', 'longitude')
    op.drop_column('bike', 'latitude')
    # ### end Alembic commands ###
