"""empty message

Revision ID: a65ab5a1cff8
Revises: 8660b8acb173
Create Date: 2022-10-11 16:45:00.337238

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a65ab5a1cff8'
down_revision = '8660b8acb173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_order', sa.Column('start_latitude', sa.Float(), nullable=True))
    op.add_column('vehicle_order', sa.Column('start_longitude', sa.Float(), nullable=True))
    op.add_column('vehicle_order', sa.Column('end_latitude', sa.Float(), nullable=True))
    op.add_column('vehicle_order', sa.Column('end_longitude', sa.Float(), nullable=True))
    op.drop_column('vehicle_order', 'end_location')
    op.drop_column('vehicle_order', 'start_location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_order', sa.Column('start_location', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('vehicle_order', sa.Column('end_location', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('vehicle_order', 'end_longitude')
    op.drop_column('vehicle_order', 'end_latitude')
    op.drop_column('vehicle_order', 'start_longitude')
    op.drop_column('vehicle_order', 'start_latitude')
    # ### end Alembic commands ###
